# Regenerate the git build stamp header. Run via `cmake -P` from a build-time
# custom target, NOT at configure time — that is the whole point: the commit a
# run records must be the commit that produced the binary, and configure-time
# capture goes stale the moment you commit.
#
#   cmake -DRETICOLO_SRC=<source dir> -DRETICOLO_OUT=<header path> -P WriteBuildStamp.cmake
#
# The header is rewritten ONLY when its content actually changes, so a normal
# edit-rebuild cycle never invalidates the TU that includes it; only a real
# commit / branch switch does.

if(NOT DEFINED RETICOLO_SRC OR NOT DEFINED RETICOLO_OUT)
    message(FATAL_ERROR "WriteBuildStamp.cmake: RETICOLO_SRC and RETICOLO_OUT are required")
endif()

function(_stamp_git out_var)
    execute_process(
        COMMAND git ${ARGN}
        WORKING_DIRECTORY "${RETICOLO_SRC}"
        OUTPUT_VARIABLE _out
        OUTPUT_STRIP_TRAILING_WHITESPACE
        RESULT_VARIABLE _rc
        ERROR_QUIET
    )
    if(NOT _rc EQUAL 0 OR _out STREQUAL "")
        set(_out "unknown")
    endif()
    set(${out_var} "${_out}" PARENT_SCOPE)
endfunction()

_stamp_git(_commit rev-parse --short HEAD)
_stamp_git(_branch rev-parse --abbrev-ref HEAD)

# A dirty tree means the binary does not correspond to `_commit` alone; say so
# in the stamp rather than silently recording a commit the sources don't match.
execute_process(
    COMMAND git status --porcelain --untracked-files=no
    WORKING_DIRECTORY "${RETICOLO_SRC}"
    OUTPUT_VARIABLE _dirty
    OUTPUT_STRIP_TRAILING_WHITESPACE
    RESULT_VARIABLE _dirty_rc
    ERROR_QUIET
)
if(_dirty_rc EQUAL 0 AND NOT _dirty STREQUAL "")
    set(_commit "${_commit}-dirty")
endif()

set(_content
"// Generated by cmake/WriteBuildStamp.cmake at BUILD time — do not edit, do not
// commit. Rewritten only when the values below actually change.
#pragma once

#define RETICOLO_STAMP_GIT_COMMIT \"${_commit}\"
#define RETICOLO_STAMP_GIT_BRANCH \"${_branch}\"
")

set(_old "")
if(EXISTS "${RETICOLO_OUT}")
    file(READ "${RETICOLO_OUT}" _old)
endif()
if(NOT _old STREQUAL _content)
    file(WRITE "${RETICOLO_OUT}" "${_content}")
    message(STATUS "reticolo: build stamp → ${_commit} (${_branch})")
endif()
